import {defineConfig} from "@anio-software/enkore"
import {defineTargetOptions} from "@anio-software/enkore.target-js-hybrid-lite"
import {
	generateFactoryWithInstantiationFile
} from "@anio-software/enkore.target-js-hybrid-lite/autogenerate"

export const config: unknown = defineConfig({
	target: {
		name: "js-hybrid-lite",
		options: defineTargetOptions({
			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			publish: [{
				registry: "anioSoftware"
			}]
		})
	},

	autogeneratedFiles: [
		...generateFactoryWithInstantiationFile({
			source: "project/src/randomIdentifierSync.ts",
			destination: "project/export/randomIdentifierSyncFactory.ts"
		})
	]
})
